### ISSUE TITLE
Delete tweets without unlike

### ISSUE THREAD

**Issue by ofk** [caarlos0/twitter-cleaner#7]
twitter-cleaner was very useful!

I would be better if twitter-cleaner had the option to delete tweets without unlike.

For example,
```
$ twitter-cleaner --delete=true --unlike=false
  OR
$ twitter-cleaner --skip-unlike
```

**Comment by caarlos0** [comment]
happy to accept a PR :)

**Comment by caarlos0** [comment]
please refer and test #9 

thanks!
